CREATE TABLE characters (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    genero VARCHAR(10) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    ocupacao VARCHAR(255) NOT NULL,
    afiliacao VARCHAR(255) NOT NULL,
    aldeia VARCHAR(255) NOT NULL,
    vila VARCHAR(255) NOT NULL,
    kekkei_genkai VARCHAR(255),
    diferencial VARCHAR(255),
    patente VARCHAR(50)
);

INSERT INTO characters (
    name, genero, estado, ocupacao, afiliacao, aldeia, vila, kekkei_genkai, diferencial, patente
) VALUES
('Naruto Uzumaki', 'Masculino', 'Vivo', 'Hokage', 'Monte Myouboku', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Jinchuuriki', 'Genin'),
('Sakura Haruno', 'Feminino', 'Viva', 'Fundadora do Hospital de Konoha', 'Floresta Shikkotsu', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Byakugou', 'Jounin'),
('Sasuke Uchiha', 'Masculino', 'Vivo', 'Líder do Clã Uchiha', 'Caverna Ryuuchi', 'Aldeia da Folha', 'Konohagakure', 'Rinnegan', 'Mangekyou Eterno', 'Genin'),
('Kakashi Hatake', 'Masculino', 'Vivo', 'Hokage', 'Forças Aliadas Shinobi', 'Aldeia da Folha', 'Konohagakure', 'Sharingan', 'Copiar Jutsus', 'Jounin'),
('Hinata Hyuuga', 'Feminino', 'Viva', 'Dona de Casa', 'Forças Aliadas Shinobi', 'Aldeia da Folha', 'Konohagakure', 'Byakugan', 'Punho dos Leões Gêmeos', 'Jounin'),
('Shikamaru Nara', 'Masculino', 'Vivo', 'Hokage', 'Forças Aliadas Shinobi', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Inteligência', 'Jounin'),
('Chouji Akimichi', 'Masculino', 'Vivo', 'Líder do Clã Akimichi', 'Forças Aliadas Shinobi', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Expansão', 'Chuunin'),
('Ino Yamanaka', 'Feminino', 'Viva', 'Líder do Clã Yamanaka', 'Forças Aliadas Shinobi', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Nenhum', 'Jounin'),
('Neji Hyuuga', 'Masculino', 'Morto', 'Membro da Família Secundária do Clã Hyuga', 'Forças Aliadas Shinobi', 'Aldeia da Folha', 'Konohagakure', 'Byakugan', 'Nenhum', 'Jounin'),
('Tenten', 'Feminino', 'Viva', 'Ninja Especialista em Armas', 'Forças Aliadas Shinobi', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Nenhum', 'Chuunin'),
('Rock Lee', 'Masculino', 'Vivo', 'Líder do Time 5', 'Forças Aliadas Shinobi', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Não pode usar Ninjutsu', 'Jounin'),
('Iruka Umino', 'Masculino', 'Vivo', 'Diretor da Academia Ninja', 'Forças Aliadas Shinobi', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Nenhum', 'Jounin'),
('Jiraiya', 'Masculino', 'Morto', 'Sannin', 'Monte Myouboku', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Imune a Genjutsu', 'Sannin'),
('Tsunade', 'Feminino', 'Morto', 'Hokage', 'Floresta Shikkotsu', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Byakugou', 'Sannin'),
('Minato Namikaze', 'Masculino', 'Morto', 'Hokage', 'Monte Myouboku', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Velocidade', 'Jounin'),
('Hiruzen Sarutobi', 'Masculino', 'Morto', 'Hokage', 'Konohagakure', 'Aldeia da Folha', 'Konohagakure', 'Não possui', '5 Elementos', 'Jounin'),
('Kabuto Yakushi', 'Masculino', 'Vivo', 'Braço direito do Orochimaru', 'Caverna Ryuuchi', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Modo Sábio do Orochimaru', 'Jounin'),
('Orochimaru', 'Masculino', 'Vivo', 'Renegado', 'Akatsuki', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'IMortol', 'Sannin'),
('Hashirama Senju', 'Masculino', 'Morto', 'Hokage', 'Konohagakure', 'Aldeia da Folha', 'Konohagakure', 'Estilo Madeira', 'Mokuton', 'Sem patente'),
('Tobirama Senju', 'Masculino', 'Morto', 'Hokage', 'Konohagakure', 'Aldeia da Folha', 'Konohagakure', 'Não possui', 'Criador de Jutsu', 'Sem patente'),
('Nagato', 'Masculino', 'Morto', 'Líder da Akatsuki', 'Akatsuki', 'Aldeia Oculta da Chuva', 'Amegakure', 'Rinnegan', 'Controle de Seis Caminhos', 'Sem patente'),
('Konan', 'Feminino', 'Morto', 'Membro da Akatsuki', 'Akatsuki', 'Aldeia Oculta da Chuva', 'Amegakure', 'Não possui', 'Papéis Explosivos', 'Jounin'),
('Itachi Uchiha', 'Masculino', 'Morto', 'Ex-membro da Akatsuki', 'Akatsuki', 'Aldeia da Folha', 'Konohagakure', 'Sharingan', 'Amaterasu, Tsukuyomi', 'Jounin'),
('Kisame Hoshigaki', 'Masculino', 'Morto', 'Ex-membro da Akatsuki', 'Akatsuki', 'Aldeia Oculta da Névoa', 'Kirigakure', 'Triton (Kekkei Genkai)', 'Espada Samehada', 'Jounin'),
('Deidara', 'Masculino', 'Morto', 'Ex-membro da Akatsuki', 'Akatsuki', 'Aldeia Oculta da Pedra', 'Iwagakure', 'Não possui', 'Explosivos de Argila', 'Jounin'),
('Sasori', 'Masculino', 'Morto', 'Ex-membro da Akatsuki', 'Akatsuki', 'Aldeia Oculta da Areia', 'Sunagakure', 'Não possui', 'Marionetes', 'Jounin'),
('Hidan', 'Masculino', 'Morto', 'Ex-membro da Akatsuki', 'Akatsuki', 'Aldeia Oculta da Nuvem', 'Kumogakure', 'Não possui', 'IMortol', 'Jounin'),
('Kakuzu', 'Masculino', 'Morto', 'Ex-membro da Akatsuki', 'Akatsuki', 'Aldeia Oculta da Cachoeira', 'Takigakure', 'Não possui', 'Controle de Corações', 'Jounin'),
('Zetsu', 'Masculino', 'Morto', 'Ex-membro da Akatsuki', 'Akatsuki', '-', '-', 'Não possui', 'Forma Subterrânea', 'Jounin'),
('Obito Uchiha', 'Masculino', 'Morto', 'Líder da Akatsuki', 'Akatsuki', 'Aldeia Oculta da Folha', 'Konohagakure', 'Sharingan, Rinnegan', 'Manipulação do Tempo e Espacial', 'Chuunin'),
('Black Zetsu', 'Masculino', 'Morto', '
Vigia da Akatsuki', 'Akatsuki', '-', '-', 'Não possui', 'Manipulação da Mente de Madara', 'Jounin'),
('White Zetsu', 'Masculino', 'Morto', '
Vigia da Akatsuki', 'Akatsuki', '-', '-', 'Não possui', 'Cópia e Imitação', 'Jounin'),
('Madara Uchiha', 'Masculino', 'Morto', 'Ex-membro da Akatsuki', 'Akatsuki', 'Aldeia Oculta da Folha', 'Konohagakure', 'Sharingan, Rinnegan', 'Manipulação do Tempo e Espacial', 'Sem patente'),
('A (Quarto Raikage)', 'Masculino', 'Vivo', 'Raikage', 'Forças Aliadas Shinobi', 'Aldeia Oculta da Nuvem', 'Kumogakure', 'Não possui', 'Força Bruta', 'Kage'),
('Oonoki', 'Masculino', 'Morto', 'Tsuchikage', 'Forças Aliadas Shinobi', 'Aldeia Oculta da Pedra', 'Iwagakure', 'Não possui', 'Poderes Terrestres', 'Kage'),
('Mei Terumi', 'Feminino', 'Viva', 'Mizukage', 'Forças Aliadas Shinobi', 'Aldeia Oculta da Névoa', 'Kirigakure', 'Kekkei Genkai do Fogo e Água', 'Temperamento Forte', 'Kage'),
('Gaara', 'Masculino', 'Vivo', 'Kazekage', 'Forças Aliadas Shinobi', 'Aldeia Oculta da Areia', 'Sunagakure', 'Estilo Areia', 'Controle de Areia', 'Jounin');